### ISSUE TITLE
Release 1.8.0

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#1389]
This issue is to track the stable release of 1.8.0 

### TODO 

Roughly in order: 

- [x] Merge 1.8-dev into master 
- [x] Solidify Interfaces as class or module? 
  - [x] #1372  ?
  - [x] Update GitHub to the new API 
- [x] Check graphql-client compatibility 
- Fix lingering issues: 
  - [x] ~~#1388~~ fixed by #1391 
  - [x] ~~GraphQL-Pro route helpers~~ fixed in 1.7.1
- [x] ~~Ship `.rc1`~~ I'll release another `pre` instead
- [x] Review upgrade & compatibility docs, update and add new info
- [x] Write a blog post about using the upgrader code 
- [x] Send out a "coming soon" email to the newsletter
- [x] Address outstanding issues https://github.com/rmosolgo/graphql-ruby/milestone/51
- [x] release 1.8.0
- ... 
- [x] Send a stable release announcement to the newsletter

**Comment by hmans** [comment]
Hey @rmosolgo, first of all, thank you for your work on `graphql-ruby`!

We're using it in a new project, and I've been wondering: should we start with the current pre-release of 1.8.0 right away, or should we stick to 1.7.x and wait until the first RC or so? Thanks!

**Comment by hmans** [comment]
Our project isn't going to be terribly large, so a certain amount of refactoring to keep up with 1.8's development is perfectly acceptable. Thanks for the heads-up!

**Comment by jcbpl** [comment]
@rmosolgo I'll echo the thanks for all your hard work, the 1.8 changes are really great.

I'm starting to migrate a project over to the class-based API, and I'm trying to decide on if/how to change the way we're dynamically generating types. I think there are a number of ways it could be done (including leveraging `#to_graphql`), but I'm wondering if you've had any ideas yet about what an approach that doesn't use `GraphQL::ObjectType.define` might look like, or if that's even worth trying right now.

**Comment by rmosolgo** [comment]
I think it will be `Class.new(BaseObject) { graphql_name(generated_type_name) ... }`, what do you think of that?

**Comment by rmosolgo** [comment]
Could you share an example of how ` Graph::Factories::Metric.define` is used? Just curious to get a sense of it.

**Comment by jcbpl** [comment]
Right now I'm just calling it from `Graph::Objects::Interval` (`Metric` is an AR model):

```ruby
class Graph::Objects::Interval < Graph::Objects::Base
  Metric.all.each do |metric|
    Graph::Factories::Metric.define(metric: metric)
  end
end
```

Ideally though I think I want to be able to call `#define` when I create Metric record(s) in a test, and have the fields and types be added so that I could verify them in a GraphQL test. I also probably want to call it from an initializer (rather than from `Interval`) in dev and prod.

**Comment by rmosolgo** [comment]
Thanks for sharing. I tried to understand it by inlining a lot of the code. Then I made a few changes: 

- Remove `def count` since the implementation there is the default behavior
- Use `define_method` instead of a resolve proc
- Instead of initializing a Field instance and using `add_field`, use the `field(...)` helper 

In my case it turned out looking like this: 

```ruby
class Graph::Objects::Interval < Graph::Objects::Base
  # Read some objects from the database 
  Metric.all.each do |metric|
    # Generate a field from each object, using `source` as the name 
    field_name = metric.source
    # Don't override an existing field 
    if fields[field_name].nil?
      # Generate a return type for this field. It has a `count` field.
      return_type = Class.new(Graph::Objects::Base) do
        graphql_name "#{field_name.classify}Posts"
        field :count, Integer, null: false
      end

      # Define a field with the same name, returning the generated return type 
      field(field_name, return_type, null: false)

      # Implement the field with a method 
      define_method(field_name) do 
        @object.where(source: field_name)
      end 
    end
  end
end
```

Like you said, maybe for your app you want to reorganize it a bit to fit your flow, but I thought it was a fun exercise and maybe a fresh perspective would come in handy! Thanks again for sharing your use case a bit.

**Comment by jcbpl** [comment]
Thanks! The inline approach is pretty much where I started. 😄 

I just realized I could use `irep_node` to infer the field name in a resolve method directly on `Interval`:

```ruby
class Graph::Factories::Metric
  def self.define(metric:)
    field_name = metric.source

    if Graph::Objects::Interval.fields[field_name].nil?
      return_type = Graph::Objects::PostSource.create(field_name)
      Graph::Objects::Interval.field(field_name, return_type, null: false,
        method: :resolve_post_source, extras: [:irep_node])
    end
  end
end

class Graph::Objects::PostSource < Graph::Objects::Base
  def self.create(source)
    Class.new(self) do
      graphql_name "#{source.classify}Posts"
    end
  end

  field :count, Integer, null: false
end

class Graph::Objects::Interval < Graph::Objects::Base
  def resolve_post_source(irep_node:)
    object.where(source: irep_node.name)
  end
end
```

I'm pretty happy with this approach—no need for separate `Field`s, and it eliminates any potential confusion around what's in scope in `define_method` or `class_eval`, since the resolver in the usual place.

I think the only slight improvement might be a way to get `field_name` without using `irep_node`... `extras` might be the only thing that feels slightly out of place to me in the new API.

**Comment by rmosolgo** [comment]
Cool! The only thing I would say is to use `irep_node.definition_name` instead. If the query uses a field alias, then `.name` will return the alias, not the real field name. `extras:` _is_ a bit of a hack ... but it'll do for now 😆
