### ISSUE TITLE
AST improvements

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#1657]
I want to improve AST manipulation options in 1.9, including some breaking changes: 

- Immutable AST nodes (breaking change)
  - [x] replace attr_accessor -> attr_reader (#1338)
  - [x] freeze `.children`, `.directives` and other attached arrays (bc940ba)
- ~~Add `Node#path` and `Node#parent`~~ I decided against this because it doesn't support efficient modification, see #1790
    - ~~Since the nodes are immutable, we can cache these on the nodes themselves~~ 
    - ~~[ ] `Node#parent` references the node where `self` is a member of `children`~~
    - ~~[ ] `Node#path` is the static path to this node in the query string (see ... `TypeStack`, I think, where this is currently implemented)~~
    - ~~[ ] consider removing `parent` from method-based visitor?~~
- Improve `Language::Visitor` 
  - [x] Build a method-based hook API (#1290) 
  - [x] Add manipulation options like GraphQL-JS (#1740)
  - [x] Deprecate `.enter <<` usage (#2017)

Also, fix some things  that this will break: 

- [x] (fixed) GraphQL::Client will be broken 
- [x] ([logged](https://github.com/rmosolgo/graphql-libgraphqlparser-ruby/issues/30)) Make sure GraphQL::Libgraphqlparser will still work
- Other broken things to fix?
