### ISSUE TITLE
Release 1.9.0

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#1884]
This is a checklist and tracking issue for the next minor version, 1.9.0 

`1.9-dev` build status: [![Build Status](https://travis-ci.org/rmosolgo/graphql-ruby.svg?branch=1.9-dev)](https://travis-ci.org/rmosolgo/graphql-ruby)

- `GraphQL::Execution::Interpreter`, a new runtime 
  - [x] Implement it: #1394 
  - [x] Implement an analyzer API without irep_nodes: #1841 
  - [x] Cash in on the new interpreter being AST-only: don't run `Rewrite` for it. Hook up AST analyzers instead. #1918 #2005 
  - [x] ~~What to do with Authorization analyzer, can we leave it behind?~~ Yes, we're gonna leave it behind.
  - [x] Profile it #1886 
  - [x] Try it in our app
  - [x] Document incompatibilities & migration strategies http://rmosolgo.github.io/blog/2019/01/29/a-new-runtime-in-graphql-ruby-1-dot-9/
  - [x] Implement Lookahead #1894, #1907 
  - [x] Rethink how Subscription root fields are handled #1930 
  - [x] ~~Reimplement GraphQL Backtrace for interpreter~~ Stashed some things in context #1989 
  - [x] Support custom directives
    - [x] #2055 
    - [x] Docs ed20cda9d
- [x] Field extensions
  - Document breaking change to custom connections: their `args` input is now a symbol-keyed hash, not a GraphQL::Query::Arguments instance
- [x] AST Changes, tracked at: #1657 
  - graphql-libgraphql-parser is broken, not sure what to do there: https://github.com/rmosolgo/graphql-libgraphqlparser-ruby/issues/30
- [x] Make `bubble_errors false` the default Schema configuration #2013 #2069
- ~~Make static validation errors `extensions` optional~~ I'm going to leave it as-is for now, we can do this if needed.
- [x] Revisit `experimental: true` in docs and remove it where appropriate
- [x] Rethink perf of visitor API (#2070)
- [x] Make graphql-batch not-broken (https://github.com/shopify/graphql-batch/issues/93)

**Comment by rmosolgo** [comment]
It's not perfect but it's good enough: https://rubygems.org/gems/graphql/versions/1.9.0
