### ISSUE TITLE
[WIP, ignore please] Umbrella issue for differences vs graphql-js

### ISSUE THREAD

**Issue by daemonsy** [rmosolgo/graphql-ruby#2330]
## Background 

There are some inconsistencies with how `graphql-js` deals with parsing queries and validating schemas that causes **errors**.  Since `graphql-js` is used a lot by tools such as Graphiql, graphql-playground, the errors breaks those tools. 

I have the intention of submitting PRs to fix those issues, but might need both advice and help. 

Some of those issues have been reported and are still open, I'll hunt them down, link them her so we might be able to close them together. 

If you know an issue that's not tracked in the list below, feel free to add to the discussion with the reproduction steps. 

#### Schema building:

```javascript
const schema = require('./schema.json') // From Schema.execute(GraphQL::Introspection::INTROSPECTION_QUERY)
const utils = require('graphql/utilities');

utils.buildClientSchema(schema.data); 
```
This is what most tools use to build a client schema from introspection to power things like documentation, typeahead, linting etc. 

#### Query parsing

```javascript
const query = 'query { root { field } }';
const { parse } = require('graphql'); 

parse(query);
```

This is what the reference implementation sees as a syntactically valid graphql query?

#### Schema building
- [ ] ~~When an object type has no field validation, it produces error: `Error: <ObjectTypeName> fields must be an object with field names as keys or a function which returns such an object.`~~ This is allowed in newer versions of graphql-js
- [ ] ~~Multiline description strings broke graphql-playground. Is this spec related?~~ Seems to be fixed

#### Query parsing 
- [ ] An empty comment `'# comment'` is treated as a valid document by graphql-ruby but not graphql-js (Existing: https://github.com/rmosolgo/graphql-ruby/issues/2243)
