### ISSUE TITLE
Release 1.11

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#2846]
I think I want to focus this on some rework of subscriptions, which may include breaking-ish changes. 

- Simplify the system: 
  - [x] Remove need for `extend ...SubscriptionRoot` with Interpreter #2770 
  - ~~Simplify the implementation, too?~~ It'd be great but I have no vision for how it could be improved right now

- Support more flexible execution/delivery
  - [x] #2844 
- Implement improved subscription API 
  - Turns out, this can be done with what we already have. Only the implementations need updates 
  - [x] #2959 ActionCable
  - [x] Document how this works
  - [ ] Pro: Pusher, Ably and Pubnub should use this algorithm, too 
- [x] Default tests to `TESTING_INTERPRETER` #2860 
- [x] Migrate the schema-from-introspection-response code to build a class-based schema 
  - Going into 1.10.x #2876
- [x] Remove global tracer support #2936 

Maybe some other things will come up (or be suggested here)

**Comment by apuntovanini** [comment]
Hi @rmosolgo, currently (if I don't get it terribly wrong), `createRelaySubscriptionHandler` doens't pass an observer to Relay Network layer, resulting in an Uncaught TypeError: Cannot read property 'onNext' of undefined

Offeding lines  
```
received: function (payload) {
  // When we get a response, send the update to `observer`
  var result = payload.result;
  if (result && result.errors) {
      // What kind of error stuff belongs here?
      observer.onError(result.errors);
  }
  else if (result) {
      observer.onNext({ data: result.data });
  }
  if (!payload.more) {
      // Subscription is finished
      observer.onCompleted();
  }
}
```

observer is undefined. Am I doing something wrong? If yes, maybe some additional comments in docs can be helpful (let me know if you accept PR)
Thanks!

**Comment by rmosolgo** [comment]
@apuntovanini , please open a new issue if you'd like to report a bug. See https://graphql-ruby.org/development.html and https://github.com/rmosolgo/graphql-ruby/blob/master/.github/contributing.md for details about contributing to this project.

**Comment by rmosolgo** [comment]
🚢 !
