### ISSUE TITLE
Release 1.12.0

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#3056]
This is a checklist and tracking issue for the next release of GraphQL-Ruby. 

- [x] Rails-style validations for inputs (#799, #3164, #3207) : 
  - [x] min/max length (strings, lists)
  - [x] min/max (integer, float) 
  - [x] pattern (strings) 
  - [x] in (set of values, inclusion and exclusion) 
  - [x] not null (for required inputs -- to avoid explicitly-given `null`) 
  - [x] custom validation docs
  - [x] custom message options
- [x] Parallelizable data loader ~~#2483~~ #3264 
- [x] Immutable arguments objects  #3004
- [x] Extract connection/edge type behaviors into modules #2542 #3071 
- [x] First-class support for field directives #2122, #3143, PR: #3224
- [x] The library defaults to new behaviors #3145 
  - [x] Interpreter 
  - [x] Analysis::AST 
  - [x] Pagination::Connections
  - [x] Execution::Errors
- Deprecate everything that will be removed in GraphQL-Ruby 2.0, remove docs for them #3275 
  - [x] `.define`, old type classes, old field and argument classes
  - [x] SerialExecution, `GraphQL::Execution::Execute`, Query::ArgumentsCache (because interpreter has a new one)
  - [x] Old `Relay` helpers (connections, mutation, node Id)
  - [x] Old execution extension points: field instrumentation, middleware
  - [x] Irep & irep analysis
  - [x] GraphQL::Compatibility -- no external runtimes are supported, no external parsers are supported (libgraphqlparser-ruby hasn't worked since 1.9.x)
  - [x] Rework execution to bypass executor? 
  - [x] Schema::Validation
  - [x] Schema::Upgrader, Railtie
  - [x] Schema instance behaviors (associated with `.define`-returned instances)
  - [x] GraphQL::Function
  - [x] GraphQL::BackwardsCompatibility (which was for `.define`)
  - [x] GraphQL::DeprecatedDSL
  - [x] Legacy validator classes with `.validate`
  - [x] SCREAMING_CASE scalar type constants
  - [x] `Multiplex#run_one_legacy` etc
  - more?

**Comment by newx** [comment]
@rmosolgo if you could provide more info about the remaining TODO items, I could try to help working on some of them :)

**Comment by rmosolgo** [comment]
👋  @newx ! A couple of the big features already have open PRs. I just need to wrap those up. 

Besides that, all the parts of graphql-ruby listed above need to have deprecation warnings because they'll be removed in GraphQL-Ruby 2.0. I'm not really sure what needs to be done there. We need something that will warn _reliably_ without spamming the logs with warnings. 

I think `warn "..."` would be sufficient, as long as each warning includes: 

- What thing is deprecated
- Where the deprecated thing is being used (some part of `caller`, so that the reader knows what lines of their own code to change)
- What thing to use instead of the deprecated thing (including a usage example and/or link to documentation)  

The goal is for the deprecation warning to be so good that someone who sees it can make the required change _without_ opening an issue on github (or maybe even _without_ searching the docs!). 

If you're interested in adding some of those, feel free to pick a few items off the list and open a PR. That way we can make sure the messaging aligns with my goals above before you add a lot of them. 

There will also be some work in updating GraphQL-Ruby's own code and tests to make sure those deprecated things are not used. In my opinion, that can be done _after_ adding the warnings. (Besides, GraphQL-Ruby's own deprecated usage can help us make sure the warnings work 😆 !)

**Comment by newx** [comment]
@rmosolgo Cool. I will take a look at these and get back to you soon. Thank you

**Comment by rmosolgo** [comment]
🚢 !
