### ISSUE TITLE
Release 1.13.0

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#3274]
My hope is to make this the _last_ 1.x release, before removing all the things marked deprecated!

- [x] Add new global ID / node ID helpers, deprecate the existing ones (use Rails GlobalID? Make sure they're URL-safe, #2106)
  - Improve the gennerator output in https://github.com/rmosolgo/graphql-ruby/pull/3710
  - fixed in 1.12.20
- [x] Investigate an evented Fiber scheduler with Ruby 3 #3482 
- [x] #3684
  - fixed in 1.12.4 with #3312  and #3320 
- [x] Stop returning invalid nil errors to the client -- instead, make some way to add those to a bug tracker #3282 
  - consider, are there other errors that should be treated this way? 
  - of course, there must be a backwards-compat path 
  - Trying in https://github.com/rmosolgo/graphql-ruby/pull/3681
  - No, just recommend something better in the generator: https://github.com/rmosolgo/graphql-ruby/pull/3710
  - fixed in 1.12.20
- [x] Add new default `null: true` and `required: false`? 
  - https://github.com/rmosolgo/graphql-ruby/pull/3612
- [x] #2804 
  - https://github.com/rmosolgo/graphql-ruby/pull/3613
- [x] #3651 
- [x] Update Ruby versions in docs, gemspec, rubocop and CI #3640

**Comment by Austio** [comment]
Hello, suggestion for a feature.   Have you considered adding hooks for the resolve function in classes so that it is easy to extend in user land?

Maybe something like.  

before_resolve and after_resolve

**Comment by rmosolgo** [comment]
Thanks for the suggestion. I haven't considered it, but I certainly _could_! How about opening an issue describing the feature and how you might use it?
